version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_checkout:
      - git fetch --shallow-since=2023-01-01  || true

conda:
  environment: docs/rtd_environment.yaml

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
        - all

# Don't build any extra formats
formats: []
